FROM python:3.12-alpine

ARG VERSION

RUN mkdir /tmp/lorad
WORKDIR /tmp/lorad

COPY . .
RUN apk add ffmpeg && pip install poetry
RUN poetry build
RUN pip install dist/*.whl
RUN cp /tmp/lorad/lorad_main.py /usr/bin/lorad && chmod +x /usr/bin/lorad
RUN rm -rf /tmp/lorad

RUN ln -s /usr/share/zoneinfo/Europe/Minsk /etc/localtime

RUN echo "${VERSION}" > /version

WORKDIR /
EXPOSE 5475
EXPOSE 5476
ENTRYPOINT [ "lorad" ]