FROM localhost/locchan/lorad:latest

RUN rm -rf /resources
RUN rm /usr/bin/lorad
RUN rm -rf /tmp/lorad

RUN mkdir -p /tmp/lorad
WORKDIR /tmp/lorad

COPY . .
RUN apk add ffmpeg && pip install poetry
RUN poetry build

RUN pip install --upgrade --no-deps --force-reinstall dist/*.whl
RUN pip install --upgrade dist/*.whl

RUN cp /tmp/lorad/lorad_main.py /usr/bin/lorad && cp -rf /tmp/lorad/resources /resources
RUN rm -rf /tmp/lorad

RUN ln -sf /usr/share/zoneinfo/Europe/Minsk /etc/localtime

WORKDIR /
EXPOSE 5475
ENTRYPOINT [ "lorad" ]