#!/usr/bin/env bash

set -e
set -x

source "config"
rm -rf ./temp
mkdir -p ./temp
git clone https://github.com/Locchan/LoRaD ./temp
cd ./temp
VERSION_SHORT=$(/bin/sh getver.sh --short)
VERSION=$(/bin/sh getver.sh)

docker build --build-arg "VERSION=$VERSION" -t "$REGISTRY/${IMAGE_NAME}:$VERSION_SHORT" -t "$REGISTRY/$IMAGE_NAME:latest" -f Dockerfile_full .

cd ../
rm -rf ./temp

docker push "$REGISTRY/${IMAGE_NAME}:$VERSION_SHORT"
docker push "$REGISTRY/$IMAGE_NAME:latest"
docker image prune --force
