#!/bin/bash

set -e
set -x

mkdir -p /opt/container_storage/lorad
if docker ps --format '{{.Names}}' | grep -qx lorad; then
  printf "Already started.\n"
  exit 0
else
  docker rm lorad || :
  printf "Starting...\n"
  docker compose up -d >/dev/null
fi
