FEATURE_FLAGS = []
TEMPDIR = ""

LOCALE = ""

CURRENT_DATA_STREAMER = None

FILESTREAMER = None
YANDEX_OBJ = None

RESTREAMER = None

PLAYERS = []
CURRENT_PLAYER_NAME = ""

FLG_DEBUG = "DEBUG"
FLG_NO_DOWNLOADING = "NO_DOWNLOADING"

FEAT_FILESTREAMER = "FILESTREAMER"
FEAT_FILESTREAMER_YANDEX = "FILESTREAMER:YANDEX"
FEAT_RESTREAMER = "RESTREAMER"
FEAT_NEURONEWS = "NEURONEWS"
FEAT_REST = "REST"
FEAT_FAKE_NEWS = "FAKENEWS"
FEAT_ADS = "ADVERTISEMENTS"

TERMINAL_POWERSHELL = "powershell"

SWITCH_LOCK = False
YANDEX_STATION_CACHE = None

LOGIN_NO_SUCH_USER = 0
LOGIN_SUCCESS = 1
LOGIN_INCORRECT_PASSWORD = 2

CAP_IMBA = "ALL"
CAP_ADMIN = "ADMIN"
CAP_BASIC_USER = "BU"

RESTREAMER_DEFAULT_FORMAT = "mp3"

END_OF_TRANSCODED_DATA = b'EOTD'

EDITABLE_CONFIG_KEYS = ["ENABLED_PROGRAMS/NewsSmall/start_times"]